### ISSUE TITLE
怪物未能正常刷新

### ISSUE THREAD

**Issue by Mcayear** [SmallasWater/LittleMonster#21]
![Screenshot_20230328_201737](https://user-images.githubusercontent.com/48203962/228234741-43b76388-8ace-41f1-a25c-e9290214e5a0.jpg)

如图，没有怪物存在，但刷新时间仍然为-1。

**Comment by Mcayear** [comment]
可能在服务器没人的时候实体被close()了

**Comment by lt-name** [comment]
麻烦截图下配置文件

**Comment by Mcayear** [comment]
> 有具体触发方式吗？ 世界重载过吗？

世界没有重载过。我可以提供配置文件

插件及插件配置下载链接：https://pan.vusv.cn/AliyunDrive/temp/plugins.zip

### powernukitx服务端运行在windows系统中测试，如果需要可以下载完整的包

服务器包下载：https://pan.vusv.cn/AliyunDrive/temp/mota3.zip

java17运行环境：https://pan.vusv.cn/AliyunDrive/temp/java.zip

目录结构：
```
├─java
    └─ ....
└─mota3
    ├─command_data
    │  └─functions
    ├─libs
    ├─players
    ├─plugins
    └ ....
```

**Comment by Mcayear** [comment]
复现方法一，在启动服务器后等待怪物生成倒计时完毕再进入服务器。可以复现。

复现方法二，退出服务器后重进，怪物消失。

**Comment by lt-name** [comment]
请更新到最新版进行测试

**Comment by Mcayear** [comment]
解决了，好神奇。
