### ISSUE TITLE
没有在水中的上岸行为

### ISSUE THREAD

**Issue by Mcayear** [SmallasWater/LittleMonster#24]
追击和随机漫游 都没有上岸行为。

如视频所示：https://pan.vusv.cn/AliyunDrive/temp/SVID_20230506_125039_1.mp4

**Comment by lt-name** [comment]
视频无法查看

**Comment by Mcayear** [comment]
下面是我补充的压缩后的视频：

https://user-images.githubusercontent.com/48203962/236633493-68523141-5e26-4d62-8fa7-07274dce962e.mp4

**Comment by Mcayear** [comment]
解决了
